<ol>
    <h6><li class="fw-bold">Introduction</h6></li>
    <p>
        Welcome to Caviom.
    </p>
    <p>
        Caviom (“us”, “we”, or “our”) operates Caviom.org (hereinafter referred to as “Service”).
    </p>
    <p>
        Our Privacy Policy governs your visit to Caviom.org, and explains how we collect, safeguard and disclose information
        that results from your use of our Service.
    </p>
    <p>
        We use your data to provide and improve Service. By using Service, you agree to the collection and use of information
        in accordance with this policy. Unless otherwise defined in this Privacy.
    </p>
    <p>
        Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
    </p>
    <p>
        Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitute your
        agreement with us (“Agreement”).
    </p>

    <h6><li class="fw-bold">Definitions</h6></li>
    <p>
        SERVICE means the Caviom.org website operated by Caviom.
    </p>
    <p>
        PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other
        information either in our possession or likely to come into our possession).
    </p>
    <p>
        USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself
        (for example, the duration of a page visit).
    </p>
    <p>
        COOKIES are small files stored on your device (computer or mobile device).
    </p>
    <p>
        DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines
        the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this
        Privacy Policy, we are a Data Controller of your data.
    </p>
    <p>
        DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data
        Controller. We may use the services of various Service Providers in order to process your data more effectively.
    </p>
    <p>
        DATA SUBJECT is any living individual who is the subject of Personal Data.
    </p>
    <p>
        THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
    </p>

    <h6><li class="fw-bold">Information Collection and Use</h6></li>
    <p>
        We collect several different types of information for various purposes to provide and improve our Service to you.
    </p>

    <h6><li class="fw-bold">Types of Data Collected</h6></li>
    <h6 class="fw-bold">Personal Data</h6>
    <p>
        While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to
        contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
        <ol>
            <li>Email address</li>
            <li>First name, middle name, and last name</li>
            <li>Telephone and Cellphone number</li>
            <li>Address, City, Province, Barangay, Postal Code</li>
            <li>Cookies and Usage Data</li>
        </ol>
    </p>
    <p>
        We may use your Personal Data to contact you for marketing or promotional materials, and other information that may be of
        interest to you. You may opt-out of receiving any, or all, of these communications from us by following the unsubscribe link.
    </p>

    <h6 class="fw-bold">Usage Data</h6>
    <p>
        We may also collect information that your browser sends whenever you visit our Service or when you access Service by or
        through any device (“Usage Data”).
    </p>
    <p>
        This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type,
        browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages,
        unique device identifiers and other diagnostic data.
    </p>
    <p>
        When you access Service with a device, this Usage Data may include information such as the type of device you use, your
        device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique
        device identifiers and other diagnostic data.
    </p>

    <h6 class="fw-bold">Location Data</h6>
    <p>
        We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data
        to provide features of our Service, to improve and customize our Service.
    </p>
    <p>
        You can enable or disable location services when you use our Service at any time by way of your device settings.
    </p>

    <h6 class="fw-bold">Tracking Cookies Data</h6>
    <p>
        We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
    </p>
    <p>
        Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your
        browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and
        scripts to collect and track information and to improve and analyze our Service.
    </p>
    <p>
        You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not
        accept cookies, you may not be able to use some portions of our Service.
    </p>
    <p>
        Examples of Cookies we use:
    </p>
    <ol>
        <li>
            <h6 class="fw-bold">Session Cookies</h6>
            <p>We use Session Cookies to operate our Service.</p>
        </li>
        <li>
            <h6 class="fw-bold">Preference Cookies</h6>
            <p>We use Preference Cookies to remember your preferences and various settings.</p>
        </li>
        <li>
            <h6 class="fw-bold">Security Cookies</h6>
            <p>We use Security Cookies for security purposes.</p>
        </li>
        <li>
            <h6 class="fw-bold">Advertising Cookies</h6>
            <p>Advertising Cookies are used to serve you with advertisements that may be
            relevant to you and your interests.</p>
        </li>
    </ol>

    <h6 class="fw-bold">Other Data</h6>
    <p>
        While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, citizenship,
        registration at place of residence and actual address, telephone number (work, mobile), details of documents on education,
        qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, social security
        (or other taxpayer identification) number, office location, and other data.
    </p>

    <h6><li class="fw-bold">Use of Data</h6></li>
    <p>
        Caviom uses the collected data for various purposes:
        <ol>
            <li>to provide and maintain our Service;</li>
            <li>to notify you about changes to our Service;</li>
            <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
            <li>to provide customer support;</li>
            <li>to gather analysis or valuable information so that we can improve our Service;</li>
            <li>to monitor the usage of our Service;</li>
            <li>to detect, prevent and address technical issues;</li>
            <li>to fulfill any other purpose for which you provide it;</li>
            <li>
                to carry out our obligations and enforce our rights arising from any contracts entered into between you and
                us, including for billing and collection;
            </li>
            <li>
                to provide you with notices about your account and/or subscription, including expiration and renewal notices,
                email instructions, etc.;
            </li>
            <li>
                to provide you with news, special offers, and general information about other goods, services, and events which
                we offer that are similar to those that you have already purchased or enquired about unless you have opted not to
                receive such information;
            </li>
            <li>in any other way we may describe when you provide the information;</li>
            <li>for any other purpose with your consent.</li>
        </ol>
    </p>

    <h6><li class="fw-bold">Retention of Data</h6></li>
    <p>
        We will retain Charitable Organization Data only for up to 5 years from the date of last activity recorded within an organization.
        If a charitable organization no longer holds an account and/or has become inactive for 5 years or more, it will be automatically
        considered as closed or deceased account of charitable organization. Therefore, we have the right to permanently delete all the
        data of your charitable organization, including all of its users. We are not required to provide data relating to any transaction
        stored of the Charitable Organization prior to the date of account and/or charitable organization deletion.
    </p>
    <p>
        We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period,
        except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally
        obligated to retain this data for longer time periods
    </p>

    <h6><li class="fw-bold">Transfer of Data</h6></li>
    <p>
        Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your
        state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your
        jurisdiction.
    </p>
    <p>
        If you are located outside the Philippines and choose to provide information to us, please note that we transfer the data,
        including Personal Data, to the Philippines and process it here.
    </p>
    <p>
        Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
    </p>
    <p>
        Caviom will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this
        Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are
        adequate controls in place including the security of your data and other personal information.
    </p>

    <h6><li class="fw-bold">Disclosure of Data</h6></li>
    <p>
        We may disclose personal information that we collect, or you provide:
        <ol>
            <h6><li class="fw-bold">Disclosure for Law Enforcement.</h6></li>
            <p>
                Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response
                to valid requests by public authorities.
            </p>

            <h6><li class="fw-bold">Business Transaction.</h6></li>
            <p>
                If we or our subsidiaries are involved in a merger, acquisition, or asset sale, your Personal Data may be transferred.
            </p>

            <h6><li class="fw-bold">Other cases. We may disclose your information also:</h6></li>
            <ol>
                <li>to our subsidiaries and affiliates;</li>
                <li>to contractors, service providers, and other third parties we use to support our business;</li>
                <li>to fulfill the purpose for which you provide it;</li>
                <li>for the purpose of including your company's logo on our website;</li>
                <li>for any other purpose disclosed by us when you provide the information;</li>
                <li>with your consent in any other cases;</li>
                <li>
                    if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company,
                    our customers, or others.
                </li>
            </ol>
        </ol>
    </p>

    <h6><li class="fw-bold">Security of Data</h6></li>
    <p>
        The security of your data is important to us but remember that no method of transmission over the Internet or method of
        electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we
        cannot guarantee its absolute security.
    </p>

    <h6><li class="fw-bold">Your Data Protection Rights Under Data Privacy Act of 2012</h6></li>
    <p>
        If you are a Filipino resident, you have certain data protection rights, covered by Republic Act 10173, or known as Data
        Privacy Act 2012.
    </p>
    <p>
        We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
    </p>
    <p>
        If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems,
        please email us at <a href="mailto:support@caviom.org">support@caviom.org</a>.
    </p>
    <p>
        In certain circumstances, you have the following data protection rights:
    </p>
    <p>
        <ol>
            <li>the right to access, update, or to delete the information we have on you;</li>
            <li>
                the right of rectification. You have the right to have your information rectified if that information is inaccurate or
                incomplete;
            </li>
            <li>the right to object. You have the right to object to our processing of your Personal Data;</li>
            <li>
                the right of restriction. You have the right to request that we restrict the processing of your personal information;
            </li>
            <li>
                the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured,
                machine-readable, and commonly used format;
            </li>
            <li>
                the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your
                consent to process your personal information.
            </li>
        </ol>
    </p>
    <p>
        Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not
        be able to provide Service without some necessary data.
    </p>
    <p>
        You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data.
        For more information, please contact your local data protection authority in the National Privacy Commission (NPC).
    </p>

    <h6><li class="fw-bold">Service Providers</h6></li>
    <p>
        We may employ third-party companies and individuals to facilitate our Service <strong>(“Service Providers”)</strong>,
        provide Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used.
    </p>
    <p>
        These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated
        not to disclose or use it for any other purpose.
    </p>

    <h6><li class="fw-bold">Analytics</h6></li>
    <p>
        We may use third-party Service Providers to monitor and analyze the use of our Service.
    </p>

    <h6><li class="fw-bold">CI/CD tools</h6></li>
    <p>
        We may use third-party Service Providers to automate the development process of our Service.
    </p>

    <h6><li class="fw-bold">Behavioral Remarketing</h6></li>
    <p>
        We may use remarketing services to advertise on third-party websites to you after you visited our Service.
        We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.
    </p>

    <h6><li class="fw-bold">Links to Other Sites</h6></li>
    <p>
        Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you will be
        directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
    </p>
    <p>
        We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party
        sites or services.
    </p>

    <h6><li class="fw-bold">Children's Privacy</h6></li>
    <p>
        Our Services are not intended for use by children under the age of 18 (“Child” or “Children”). We do not knowingly
        collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with
        Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification
        of parental consent, we take steps to remove that information from our servers.

    </p>

    <h6><li class="fw-bold">Changes to This Privacy Policy</h6></li>
    <p>
        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy
        on this page.
    </p>
    <p>
        We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective, and update
        the “effective date” at the top of this Privacy Policy.
    </p>
    <p>
        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective
        when they are posted on this page.
    </p>

    <h6><li class="fw-bold">Contact Us</h6></li>
    <p>
        If you have any questions about this Privacy Policy, please contact us by email:
        <a href="mailto:support@caviom.org">support@caviom.org</a>. This disclaimer was created for https://caviom.org by a free
        tool PolicyMaker.io on 2022-08-10.
    </p>
</ol>